// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tus/tusd/v2/pkg/alistore (interfaces: AliReader,AliAPI)

// Package alistore_test is a generated GoMock package.
package alistore_test

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	alistore "github.com/tus/tusd/v2/pkg/alistore"
)

// MockAliReader is a mock of AliReader interface.
type MockAliReader struct {
	ctrl     *gomock.Controller
	recorder *MockAliReaderMockRecorder
}

// MockAliReaderMockRecorder is the mock recorder for MockAliReader.
type MockAliReaderMockRecorder struct {
	mock *MockAliReader
}

// NewMockAliReader creates a new mock instance.
func NewMockAliReader(ctrl *gomock.Controller) *MockAliReader {
	mock := &MockAliReader{ctrl: ctrl}
	mock.recorder = &MockAliReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAliReader) EXPECT() *MockAliReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAliReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAliReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAliReader)(nil).Close))
}

// ContentType mocks base method.
func (m *MockAliReader) ContentType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentType")
	ret0, _ := ret[0].(string)
	return ret0
}

// ContentType indicates an expected call of ContentType.
func (mr *MockAliReaderMockRecorder) ContentType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentType", reflect.TypeOf((*MockAliReader)(nil).ContentType))
}

// Read mocks base method.
func (m *MockAliReader) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockAliReaderMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockAliReader)(nil).Read), arg0)
}

// Remain mocks base method.
func (m *MockAliReader) Remain() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remain")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Remain indicates an expected call of Remain.
func (mr *MockAliReaderMockRecorder) Remain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remain", reflect.TypeOf((*MockAliReader)(nil).Remain))
}

// Size mocks base method.
func (m *MockAliReader) Size() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockAliReaderMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockAliReader)(nil).Size))
}

// MockAliAPI is a mock of AliAPI interface.
type MockAliAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAliAPIMockRecorder
}

// MockAliAPIMockRecorder is the mock recorder for MockAliAPI.
type MockAliAPIMockRecorder struct {
	mock *MockAliAPI
}

// NewMockAliAPI creates a new mock instance.
func NewMockAliAPI(ctrl *gomock.Controller) *MockAliAPI {
	mock := &MockAliAPI{ctrl: ctrl}
	mock.recorder = &MockAliAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAliAPI) EXPECT() *MockAliAPIMockRecorder {
	return m.recorder
}

// ComposeObjects mocks base method.
func (m *MockAliAPI) ComposeObjects(arg0 context.Context, arg1 alistore.AliComposeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeObjects", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComposeObjects indicates an expected call of ComposeObjects.
func (mr *MockAliAPIMockRecorder) ComposeObjects(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeObjects", reflect.TypeOf((*MockAliAPI)(nil).ComposeObjects), arg0, arg1)
}

// DeleteObject mocks base method.
func (m *MockAliAPI) DeleteObject(arg0 context.Context, arg1 alistore.AliObjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockAliAPIMockRecorder) DeleteObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockAliAPI)(nil).DeleteObject), arg0, arg1)
}

// DeleteObjectsWithFilter mocks base method.
func (m *MockAliAPI) DeleteObjectsWithFilter(arg0 context.Context, arg1 alistore.AliFilterParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectsWithFilter", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectsWithFilter indicates an expected call of DeleteObjectsWithFilter.
func (mr *MockAliAPIMockRecorder) DeleteObjectsWithFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectsWithFilter", reflect.TypeOf((*MockAliAPI)(nil).DeleteObjectsWithFilter), arg0, arg1)
}

// FilterObjects mocks base method.
func (m *MockAliAPI) FilterObjects(arg0 context.Context, arg1 alistore.AliFilterParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterObjects", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterObjects indicates an expected call of FilterObjects.
func (mr *MockAliAPIMockRecorder) FilterObjects(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterObjects", reflect.TypeOf((*MockAliAPI)(nil).FilterObjects), arg0, arg1)
}

// GetObjectSize mocks base method.
func (m *MockAliAPI) GetObjectSize(arg0 context.Context, arg1 alistore.AliObjectParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectSize", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectSize indicates an expected call of GetObjectSize.
func (mr *MockAliAPIMockRecorder) GetObjectSize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectSize", reflect.TypeOf((*MockAliAPI)(nil).GetObjectSize), arg0, arg1)
}

// ReadObject mocks base method.
func (m *MockAliAPI) ReadObject(arg0 context.Context, arg1 alistore.AliObjectParams) (alistore.AliReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadObject", arg0, arg1)
	ret0, _ := ret[0].(alistore.AliReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadObject indicates an expected call of ReadObject.
func (mr *MockAliAPIMockRecorder) ReadObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadObject", reflect.TypeOf((*MockAliAPI)(nil).ReadObject), arg0, arg1)
}

// SetObjectMetadata mocks base method.
func (m *MockAliAPI) SetObjectMetadata(arg0 context.Context, arg1 alistore.AliObjectParams, arg2 map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetObjectMetadata", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetObjectMetadata indicates an expected call of SetObjectMetadata.
func (mr *MockAliAPIMockRecorder) SetObjectMetadata(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetObjectMetadata", reflect.TypeOf((*MockAliAPI)(nil).SetObjectMetadata), arg0, arg1, arg2)
}

// WriteObject mocks base method.
func (m *MockAliAPI) WriteObject(arg0 context.Context, arg1 alistore.AliObjectParams, arg2 io.Reader) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteObject", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteObject indicates an expected call of WriteObject.
func (mr *MockAliAPIMockRecorder) WriteObject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteObject", reflect.TypeOf((*MockAliAPI)(nil).WriteObject), arg0, arg1, arg2)
}
